# ==============================================================================
# Script: 03_01_fit_over_and_undersampled_random_forest_models.R
# Original file: 02_RFM_over-und_undersampling.R
#
# Purpose:
#   Fits and evaluates two Random Forest classifiers using downsampling and
#   oversampling to address class imbalance in heat-alert classification.
#
# Inputs:
#   - RFM_Input_Data.rds containing district-level daily meteorological
#     predictors, calendar variables, and observed heat-alert status
#
# Outputs:
#   - Evaluation CSV files for the 2011–2022 validation period
#   - Historical prediction CSV files for the 2000–2004 reconstruction period
#   - Confusion matrices and prediction summaries printed to the console
#   - Variable-importance and ROC diagnostics displayed in the active graphics
#     device
#
# Modeling periods:
#   Training:               2005–2010
#   Temporal validation:    2011–2022
#   Historical prediction:  2000–2004
#
# Model specifications:
#   - Downsampling with a classification threshold of 0.70
#   - Oversampling with a classification threshold of 0.95
#
# Spatial unit:
#   Harmonized German administrative districts identified by AGS
#
# Required packages:
#   tidyverse, ranger, caret, zoo, pdp, pROC
#
# Dependencies:
#   Requires the dataset generated by
#   02_02_prepare_random_forest_input_dataset.R.
#
# Repository note:
#   Paths are project-relative and assume that the working directory is set to
#   the repository root. Only path strings and explanatory comments were
#   standardized for repository publication.
# ==============================================================================

# Load required packages

library(tidyverse)
library(ranger)   
library(caret)  
library(zoo)
library(pdp)    
library(pROC)

# Load the Random Forest input dataset
data.cl_final <- read_rds(
  "data/processed/random_forest_input/RFM_Input_Data.rds"
)

# FAST MODE: Optional reduced-data execution mode 

USE_FAST_MODE <- FALSE 

if (USE_FAST_MODE) {
  set.seed(123) 
  random_ags <- sample(unique(data.cl_final$AGS), 20)
  data.input <- data.cl_final %>% filter(AGS %in% random_ags)
  cat("FAST MODE: Nur", length(random_ags), "AGS.\n")
} else {
  data.input <- data.cl_final
}

# Prepare the modeling dataset

data.model <- data.input %>%
  
  mutate(
    HW_Binary = factor(ifelse(HW_Status == 0, "no", "yes"), levels = c("no", "yes")),
    month = as.factor(month)
  )

cat("Daten bereit. Zeilen gesamt:", nrow(data.model), "\n")

# Select variables and define temporal data splits

# Variablen-Set definieren 
vars_selected <- c("Datum", "AGS", "year", "month", "day", "yday", "dow", "HW_Status", "HW_Binary",
                   "AT_Max", "temp_pop_w", "dewpoint_pop_w", "Temp_Min", 
                   "D3_AT_Max", "wind_pop_w", "radiation_max") 

data.model <- data.model %>% select(any_of(vars_selected))

# TRAINING (2005-2010)
train_data <- data.model %>% 
  filter(year >= 2005 & year <= 2010) %>%
  drop_na(HW_Binary)

# TEST / VALIDIERUNG (2011-2022)
test_future <- data.model %>% 
  filter(year >= 2011 & year <= 2022) %>%
  drop_na(HW_Binary)

# SIMULATION (2000-2004)
test_historic <- data.model %>% 
  filter(year >= 2000 & year < 2005)

cat("Training:", nrow(train_data), "| Test:", nrow(test_future), "| Sim:", nrow(test_historic), "\n")

# Define evaluation and export functions

# Funktion 1: Evaluieren & Speichern
evaluate_and_save <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Evaluierung:", name_suffix, "| Th:", threshold, "---\n")
  
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  print(confusionMatrix(pred_class, dataset$HW_Binary, positive = "yes", mode = "everything"))
  
  output <- dataset %>%
    mutate(Real = HW_Binary, Pred = pred_class, Prob_Yes = round(probs, 3))
  
  filename <- file.path(
    "outputs/random_forest_models/03_01_sampling_comparison",
    paste0("RFM_Eval_", name_suffix, "_Th", threshold, ".csv")
  )
  write.csv(output, filename, row.names = FALSE)
  cat("Gespeichert als:", filename, "\n")
}

# Funktion 2: Simulation 
simulate_only <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Simulation:", name_suffix, "| Th:", threshold, "---\n")
  
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  cat("Vorhergesagte Hitzewarnungen:\n")
  print(table(pred_class))
  
  output <- dataset %>%
    select(Datum, AGS, year, month) %>%
    mutate(Pred = pred_class, Prob_Yes = round(probs, 3))
  
  filename <- file.path(
    "outputs/random_forest_models/03_01_sampling_comparison",
    paste0("RFM_Sim_", name_suffix, "_Th", threshold, ".csv")
  )
  write.csv(output, filename, row.names = FALSE)
  cat("Gespeichert als:", filename, "\n")
}

###########################################################
## TEIL A: UNDERSAMPLING (Downsampling) -> Threshold 0.7 ##
###########################################################

cat("### START TEIL A: UNDERSAMPLING    ###\n")

# Indizes finden
idx_yes <- which(train_data$HW_Binary == "yes")
idx_no  <- which(train_data$HW_Binary == "no")

# Zufällige Auswahl der "no"-Fälle (Gleiche Anzahl wie "yes")
set.seed(42) 
idx_no_down <- sample(idx_no, length(idx_yes))

# Datensatz erstellen
train_down <- train_data[c(idx_yes, idx_no_down), ]

cat("Undersampling Training Set Größe:", nrow(train_down), "\n")

cat("Trainiere Ranger (Undersampled)...\n")
rf_model_down <- ranger(
  formula = HW_Binary ~ . - Datum - AGS - year - month - day - yday - dow - HW_Status, 
  data = train_down, 
  num.trees = 1000, 
  mtry = 3, 
  importance = "impurity",
  probability = TRUE,
  replace = TRUE,
  seed = 42,
  num.threads = 4
)

# AUSFÜHREN UNDERSAMPLING (Threshold 0.7)
evaluate_and_save(rf_model_down, test_future, "Downsampling", threshold = 0.7)
simulate_only(rf_model_down, test_historic, "Downsampling", threshold = 0.7)

#########################################################
## TEIL B: OVERSAMPLING (Upsampling) -> Threshold 0.95 ##
#########################################################

cat("### START TEIL B: OVERSAMPLING     ###\n")

# -> Indizes sind schon oben definiert (idx_yes, idx_no)

# Oversampling durchführen (Yes-Fälle vervielfachen)
set.seed(42) 
idx_yes_up <- sample(idx_yes, length(idx_no), replace = TRUE)

# Datensatz erstellen
train_up <- train_data[c(idx_no, idx_yes_up), ]

cat("Oversampling Training Set Größe:", nrow(train_up), "\n")

cat("Trainiere Ranger (Oversampled)...\n")
rf_model_up <- ranger(
  formula = HW_Binary ~ . - Datum - AGS - year - month - day - yday - dow - HW_Status, 
  data = train_up, 
  num.trees = 500,
  mtry = 3, 
  importance = "impurity",
  probability = TRUE,
  replace = TRUE,
  seed = 42,
  num.threads = 4
)

# AUSFÜHREN OVERSAMPLING (Threshold 0.95)
evaluate_and_save(rf_model_up, test_future, "Oversampling", threshold = 0.95)
simulate_only(rf_model_up, test_historic, "Oversampling", threshold = 0.95)

##############################################
## Generate model diagnostics (PLOTS & ROC) ##
##############################################

# A) Variable Importance
imp <- sort(importance(rf_model), decreasing = FALSE)
if(length(imp) > 15) imp <- tail(imp, 15) 

par(mar=c(5,10,4,2)) 
barplot(imp, main = "Top Variablen (Impurity)", horiz = TRUE, col = "darkblue", las = 1, cex.names = 0.7)

# B) ROC & Threshold Check (anhand Testdaten)
pred_roc <- predict(rf_model, test_future)$predictions[, "yes"]
roc_obj <- roc(test_future$HW_Binary, pred_roc, levels = c("no", "yes"))

plot(roc_obj, main="ROC Kurve (Testdaten 2011-2022)")
MY_THRESHOLD <- 0.7
abline(v = coords(roc_obj, x=MY_THRESHOLD, input="threshold", ret="specificity"), col="blue")
