# ==============================================================================
# Script: 03_02_fit_random_forest_without_population_weighted_predictors.R
# Original file: 02_RFM_ohne_pop_w.R
#
# Purpose:
#   Fits and evaluates an inverse-frequency-weighted Random Forest classifier
#   using meteorological predictors that exclude population-weighted exposure
#   variables.
#
# Inputs:
#   - RFM_Input_Data.rds containing district-level daily meteorological
#     predictors, calendar variables, and observed heat-alert status
#
# Outputs:
#   - Evaluation CSV file for the 2011–2022 validation period
#   - Historical prediction CSV file for the 2000–2004 reconstruction period
#   - Confusion matrices and prediction summaries printed to the console
#   - Variable-importance and ROC plots displayed in the active graphics device
#
# Modeling periods:
#   Training:               2005–2010
#   Temporal validation:    2011–2022
#   Historical prediction:  2000–2004
#
# Model specification:
#   - Inverse-frequency case weights
#   - No population-weighted meteorological predictors
#   - Classification threshold of 0.90
#
# Spatial unit:
#   Harmonized German administrative districts identified by AGS
#
# Required packages:
#   tidyverse, ranger, caret, zoo, pdp, pROC
#
# Dependencies:
#   Requires the dataset generated by
#   02_02_prepare_random_forest_input_dataset.R.
#
# Repository note:
#   Paths are project-relative and assume that the working directory is set to
#   the repository root. Only path strings and explanatory comments were
#   standardized for repository publication.
# ==============================================================================

# Load required packages

library(tidyverse)
library(ranger)   
library(caret)  
library(zoo)
library(pdp)    
library(pROC)

# Load the Random Forest input dataset
data.cl_final <- read_rds(
  "data/processed/random_forest_input/RFM_Input_Data.rds"
)

# FAST MODE: Optional reduced-data execution mode 
USE_FAST_MODE <- FALSE 

if (USE_FAST_MODE) {
  set.seed(123) 
  random_ags <- sample(unique(data.cl_final$AGS), 20)
  data.input <- data.cl_final %>% filter(AGS %in% random_ags)
  cat("FAST MODE: Nur", length(random_ags), "AGS.\n")
} else {
  data.input <- data.cl_final
}

# Prepare the modeling dataset 

data.model <- data.input %>%
  
  mutate(
    HW_Binary = factor(ifelse(HW_Status == 0, "no", "yes"), levels = c("no", "yes")),
    month = as.factor(month)
  )

cat("Daten bereit. Zeilen gesamt:", nrow(data.model), "\n")

#######################################
## SPLIT (TRAIN / TEST / SIMULATION) ##
#######################################

# Variablen-Set definieren 

vars_selected <- c("Datum", "AGS", "year", "month", "day", "yday", "dow", "HW_Status", "HW_Binary",
                   "AT_Max", "Temp_Min", "D3_AT_Max")

data.model <- data.model %>% select(any_of(vars_selected))

# TRAINING (2005-2010) - Braucht Outcome ohne NAs
train_data <- data.model %>% 
  filter(year >= 2005 & year <= 2010) %>%
  drop_na(HW_Binary, AT_Max, Temp_Min, D3_AT_Max)

# TEST / VALIDIERUNG (2011-2022) - Braucht Outcome ohne NAs
test_future <- data.model %>% 
  filter(year >= 2011 & year <= 2022) %>%
  drop_na(HW_Binary, AT_Max, Temp_Min, D3_AT_Max)

# SIMULATION (2000-2004) - Outcome egal (da oft NA oder unbekannt)
test_historic <- data.model %>% 
  filter(year >= 2000 & year < 2005)
drop_na(AT_Max, Temp_Min, D3_AT_Max)

cat("Training:", nrow(train_data), "| Test:", nrow(test_future), "| Sim:", nrow(test_historic), "\n")

##################################################################
## Calculate inverse-frequency case weights (ORGINAL STRATEGIE) ##
##################################################################

# Gewichte berechnen 
counts <- table(train_data$HW_Binary)
weights_vector <- (1 / counts[train_data$HW_Binary])
weights_vector <- as.numeric(weights_vector / sum(weights_vector) * nrow(train_data))

cat("Trainiere Ranger Modell...\n")
rf_model <- ranger(
  formula = HW_Binary ~ . - Datum - AGS - year - month - day - yday - dow - HW_Status, 
  data = train_data, 
  num.trees = 500,
  importance = "impurity",
  case.weights = weights_vector, 
  probability = TRUE,
  seed = 42,
  num.threads = 4
)
print(rf_model)

# THRESHOLD SETZEN
MY_THRESHOLD <- 0.9

#####################################
## EVALUIERUNG & EXPORT FUNKTIONEN ##
#####################################

# Funktion 1: Speichern & Evaluieren
evaluate_and_save <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Evaluierung:", name_suffix, "| Th:", threshold, "---\n")
  
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  print(confusionMatrix(pred_class, dataset$HW_Binary, positive = "yes", mode = "everything"))
  
  # Speichern
  output <- dataset %>%
    mutate(Real = HW_Binary, Pred = pred_class, Prob_Yes = round(probs, 3))
  
  write.csv(
    output,
    file.path(
      "outputs/random_forest_models/03_02_without_population_weighted_predictors",
      paste0("RFM_Eval_NoPop_", name_suffix, ".csv")
    ),
    row.names = FALSE
  )
  cat("Datei gespeichert: RFM_Eval_NoPop_", name_suffix, ".csv\n")
}

# Funktion 2: Nur Simulation (2000-2004)
simulate_only <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Simulation:", name_suffix, "| Th:", threshold, "---\n")
  
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  cat("Vorhergesagte Hitzewarnungen:\n")
  print(table(pred_class))
  
  output <- dataset %>%
    select(Datum, AGS, year, month) %>%
    mutate(Pred = pred_class, Prob_Yes = round(probs, 3))
  
  write.csv(
    output,
    file.path(
      "outputs/random_forest_models/03_02_without_population_weighted_predictors",
      paste0("RFM_Sim_NoPop_", name_suffix, ".csv")
    ),
    row.names = FALSE
  )
  cat("Datei gespeichert: RFM_Sim_NoPop_", name_suffix, ".csv\n")
}

# Funktion 3: Nur n der Konsole
check_threshold_only <- function(model, dataset, threshold) {
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  cat("\n=== TEST-LAUF THRESHOLD:", threshold, "===\n")
  print(confusionMatrix(pred_class, dataset$HW_Binary, positive = "yes", mode = "everything"))
}

#############################
## AUSFÜHREN UND SPEICHERN ##
#############################

# 1. Zukunft (mit Validierung)
evaluate_and_save(rf_model, test_future, "2011-2022", threshold = MY_THRESHOLD)

# 2. Vergangenheit (Simulation)
simulate_only(rf_model, test_historic, "2000-2004", threshold = MY_THRESHOLD)

# 3. Optional: Vergleichsschleife nochmal laufen lassen (nur Anzeige)
#cat("\n--- VERGLEICH DER THRESHOLDS (Nur Info) ---\n")
#for (th in c(0.8, 0.9, 0.95)) {
#  check_threshold_only(rf_model, test_future, threshold = th)
#}

##############################################
## Generate model diagnostics (PLOTS & ROC) ##
##############################################

# A) Variable Importance
imp <- sort(importance(rf_model), decreasing = FALSE)
if(length(imp) > 15) imp <- tail(imp, 15) 

par(mar=c(5,10,4,2)) 
barplot(imp, main = "Top Variablen (Impurity)", horiz = TRUE, col = "darkblue", las = 1, cex.names = 0.7)

# B) ROC & Threshold Check (anhand Testdaten)
pred_roc <- predict(rf_model, test_future)$predictions[, "yes"]
roc_obj <- roc(test_future$HW_Binary, pred_roc, levels = c("no", "yes"))

plot(roc_obj, main="ROC Kurve (Testdaten 2011-2022)")
