# ==============================================================================
# Script: 03_03_fit_weighted_random_forest_and_evaluate_thresholds.R
# Original file: 02_RFM_outcome_heat_alerts.R
#
# Purpose:
#   Fits an inverse-frequency-weighted Random Forest classifier for heat-alert
#   status, evaluates classification thresholds of 0.70 and 0.80, and generates
#   historical heat-alert predictions for the pre-implementation period.
#
# Inputs:
#   - RFM_Input_Data.rds containing district-level daily meteorological
#     predictors, calendar variables, and observed heat-alert status
#
# Outputs:
#   - Evaluation CSV files for the 2011–2022 validation period at thresholds
#     of 0.70 and 0.80
#   - Historical prediction CSV files for 2000–2004 at thresholds of 0.70
#     and 0.80
#   - Combined PNG figure containing variable importance and the ROC curve
#   - Confusion matrices, model characteristics, and session information
#     printed to the console
#   - In-memory objects supporting the exploratory grey-zone robustness check
#
# Modeling periods:
#   Training:               2005–2010
#   Temporal validation:    2011–2022
#   Historical prediction:  2000–2004
#
# Model specification:
#   - Predictors selected following the preceding correlation assessment
#   - Inverse-frequency case weights
#   - Classification thresholds of 0.70 and 0.80
#
# Spatial unit:
#   Harmonized German administrative districts identified by AGS
#
# Required packages:
#   tidyverse, ranger, caret, zoo, pdp, pROC
#
# Dependencies:
#   Requires the dataset generated by
#   02_02_prepare_random_forest_input_dataset.R and the predictor assessment
#   documented in 02_03_assess_predictor_correlations.R.
#
# Repository note:
#   Paths are project-relative and assume that the working directory is set to
#   the repository root. Only path strings and explanatory comments were
#   standardized for repository publication.
# ==============================================================================

# Load required packages

library(tidyverse)
library(ranger)   
library(caret)  
library(zoo)
library(pdp)    
library(pROC)

# Load the Random Forest input dataset

data.cl_final <- read_rds(
  "data/processed/random_forest_input/RFM_Input_Data.rds"
)

# FAST MODE: Optional reduced-data execution mode 
USE_FAST_MODE <- FALSE 

if (USE_FAST_MODE) {
  set.seed(123) 
  random_ags <- sample(unique(data.cl_final$AGS), 20)
  data.input <- data.cl_final %>% filter(AGS %in% random_ags)
  cat("FAST MODE: Nur", length(random_ags), "AGS.\n")
} else {
  data.input <- data.cl_final
}

# Prepare the modeling dataset

data.model <- data.input %>%
  
  mutate(
    HW_Binary = factor(ifelse(HW_Status == 0, "no", "yes"), levels = c("no", "yes")),
    month = as.factor(month)
  )

cat("Daten bereit. Zeilen gesamt:", nrow(data.model), "\n")

#######################################
## SPLIT (TRAIN / TEST / SIMULATION) ##
#######################################

# Variablen-Set definieren: Definiert und ausgewählt nach vorheriger Berechnung der Korrelation

vars_selected <- c("Datum", "AGS", "year", "month", "day", "yday", "dow", "HW_Status", "HW_Binary",
                   "AT_Max", "temp_pop_w", "dewpoint_pop_w", "Temp_Min", 
                   "D3_AT_Max", "wind_pop_w")

data.model <- data.model %>% select(any_of(vars_selected))

# TRAINING (2005-2010) 
train_data <- data.model %>% 
  filter(year >= 2005 & year <= 2010) %>%
  drop_na(HW_Binary)

# TEST / VALIDIERUNG (2011-2022) 
test_future <- data.model %>% 
  filter(year >= 2011 & year <= 2022) %>%
  drop_na(HW_Binary)

# SIMULATION (2000-2004) 
test_historic <- data.model %>% 
  filter(year >= 2000 & year < 2005)

cat("Training:", nrow(train_data), "| Test:", nrow(test_future), "| Sim:", nrow(test_historic), "\n")

#########################
## GEWICHTE & TRAINING ##
#########################

# Gewichte berechnen (Inverse Frequency)
counts <- table(train_data$HW_Binary)
weights_vector <- (1 / counts[train_data$HW_Binary])
weights_vector <- as.numeric(weights_vector / sum(weights_vector) * nrow(train_data))

cat("Trainiere Ranger Modell...\n")
rf_model <- ranger(
  formula = HW_Binary ~ . - Datum - AGS - year - month - day - yday - dow - HW_Status, 
  data = train_data, 
  num.trees = 500,
  importance = "impurity",
  case.weights = weights_vector, 
  probability = TRUE,
  seed = 42,
  num.threads = 4
)
print(rf_model)

########################################
## ANALYSE & GRAFIK-EXPORT FÜR ANHANG ##
########################################

# 1. Speicherort für die Grafik definieren (als kombinierte PNG-Datei)
png(
  "outputs/random_forest_models/03_03_weighted_threshold_comparison/RFM_Appendix_Plots.png",
  width = 2400,
  height = 1200,
  res = 300
)
par(mfrow = c(1, 2)) 

# ---- PLOT A: Variable Importance ----

imp <- sort(importance(rf_model), decreasing = FALSE)
par(mar = c(5, 8, 4, 2)) 
barplot(imp, 
        main = "A) Variable Importance (Impurity)", 
        horiz = TRUE, 
        col = "darkblue", 
        las = 1, 
        cex.names = 0.8,
        cex.main = 0.85) 

# ---- PLOT B: ROC-Kurve mit Threshold-Marker ----

pred_roc <- predict(rf_model, test_future)$predictions[, "yes"]
roc_obj <- roc(test_future$HW_Binary, pred_roc, levels = c("no", "yes"))

# Basis-Kurve plotten
plot(roc_obj, 
     main = "B) ROC Curve (Test Data 2011-2022)", 
     col = "darkred", 
     lwd = 3,
     cex.main = 0.85) 

# Bestimmung der Koordinaten für den 0.8 Threshold
coords_08 <- coords(roc_obj, x = 0.8, input = "threshold", ret = c("specificity", "sensitivity"))

# Den 0.8-Punkt auf der Kurve einzeichnen
points(x = coords_08$specificity, y = coords_08$sensitivity, col = "black", pch = 19, cex = 1.5)
text(x = coords_08$specificity, y = coords_08$sensitivity, labels = "  Th = 0.8", adj = 0, cex = 0.9, font = 2)

# Grafikkarte schließen und Datei speichern
dev.off()

##########################
## EVALUIERUNG & EXPORT ##
##########################

# Funktion 1: Mit Confusion Matrix & Speichern
evaluate_and_save <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Evaluierung:", name_suffix, "| Th:", threshold, "---\n")
  
  # Predict
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  # Matrix
  print(confusionMatrix(pred_class, dataset$HW_Binary, positive = "yes", mode = "everything"))
  
  # Save 
  output <- dataset %>%
    mutate(Real = HW_Binary, Pred = pred_class, Prob_Yes = round(probs, 3))
  
  filename <- file.path(
    "outputs/random_forest_models/03_03_weighted_threshold_comparison",
    paste0("RFM_Eval_", name_suffix, "_Th", threshold, ".csv")
  )
  write.csv(output, filename, row.names = FALSE)
  cat("Gespeichert als:", filename, "\n")
}

# Funktion 2: Nur Simulation (für 2000-2004)
simulate_only <- function(model, dataset, name_suffix, threshold) {
  cat("\n--- Simulation:", name_suffix, "| Th:", threshold, "---\n")
  
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  cat("Vorhergesagte Hitzewarnungen:\n")
  print(table(pred_class))
  
  output <- dataset %>%
    select(Datum, AGS, year, month) %>%
    mutate(Pred = pred_class, Prob_Yes = round(probs, 3))
  
  filename <- file.path(
    "outputs/random_forest_models/03_03_weighted_threshold_comparison",
    paste0("RFM_Sim_", name_suffix, "_Th", threshold, ".csv")
  )
  write.csv(output, filename, row.names = FALSE)
  cat("Gespeichert als:", filename, "\n")
}

# Funktion 3: Nur anzeigen lassen
check_threshold_only <- function(model, dataset, threshold) {
  probs <- predict(model, dataset)$predictions[, "yes"]
  pred_class <- factor(ifelse(probs >= threshold, "yes", "no"), levels = c("no", "yes"))
  
  cat("\n==============================================\n")
  cat(" TEST-LAUF MIT THRESHOLD:", threshold, "\n")
  cat("==============================================\n")
  print(confusionMatrix(pred_class, dataset$HW_Binary, positive = "yes", mode = "everything"))
}

##################################
## AUSFÜHREN (BEIDE THRESHOLDS) ##
##################################

cat("### START: BERECHNUNG FÜR THRESHOLD 0.7 ###\n")

# 1. Zukunft (mit Validierung) - 0.7
evaluate_and_save(rf_model, test_future, "2011-2022", threshold = 0.7)

# 2. Vergangenheit (Simulation) - 0.7
simulate_only(rf_model, test_historic, "2000-2004", threshold = 0.7)

cat("### START: BERECHNUNG FÜR THRESHOLD 0.8 ###\n")

# 3. Zukunft (mit Validierung) - 0.8
evaluate_and_save(rf_model, test_future, "2011-2022", threshold = 0.8)

# 4. Vergangenheit (Simulation) - 0.8
simulate_only(rf_model, test_historic, "2000-2004", threshold = 0.8)

# Schnell-Check am Ende in der Konsole
cat("\n--- ZUSAMMENFASSUNG DER ERGEBNISSE ---\n")
for (th in c(0.7, 0.8)) {
  check_threshold_only(rf_model, test_future, threshold = th)
}

# Inactive optional code for partial-dependence analysis
# top_var <- names(tail(imp, 1))[1]
# pd <- partial(rf_model, pred.var = top_var, train = train_data[sample(nrow(train_data), 5000),], prob = TRUE, which.class = 2) 
# plotPartial(pd, main = paste("PDP:", top_var), lwd = 2, col = "red")

# Vorhersagewahrscheinlichkeiten für die historische Phase berechnen
pred_prob_hist <- predict(rf_model, data = data_historical)$predictions[, "yes"]

# Haupt-Klassifikation mit dem optimalen Threshold von 0.8
data_historical$HW_predicted <- ifelse(pred_prob_hist >= 0.8, 1, 0)

# Wackelkandidaten um den Threshold herum identifizieren (Grauzone)
data_historical$in_grey_zone <- pred_prob_hist >= 0.75 & pred_prob_hist <= 0.85

# Bereinigter Datensatz für die Robustheitsprüfung des DiD
data_hist_robust <- subset(data_historical, in_grey_zone == FALSE)

# Report model and software information for reproducibility

print(rf_model)

rf_model$mtry
rf_model$min.node.size

packageVersion("ranger")
R.version.string
sessionInfo()

nrow(train_data)
nrow(test_future)
nrow(test_historic)

table(train_data$HW_Binary)
table(test_future$HW_Binary)
