# ==============================================================================
# Script: 02_03_assess_predictor_correlations.R
# Original file: Korrelationsmatrix_Berechnung.R
#
# Purpose:
#   Calculates and visualizes Pearson correlations among the candidate variables
#   considered for Random Forest model development and identifies variables
#   exceeding the prespecified correlation cutoff of 0.95.
#
# Inputs:
#   - The in-memory object data.cl_final generated by
#     02_02_prepare_random_forest_input_dataset.R
#
# Outputs:
#   - A lower-triangular correlation-matrix plot displayed in the active
#     graphics device
#   - A console output listing variables identified by the applied
#     correlation cutoff
#
# Spatial unit:
#   Harmonized German administrative districts identified by AGS
#
# Temporal coverage:
#   2000–2022
#
# Required packages:
#   tidyverse, ggcorrplot, caret
#
# Dependencies:
#   This script requires data.cl_final to be available in the active R session.
#   It therefore must be executed after
#   02_02_prepare_random_forest_input_dataset.R in the same R session.
#
# Repository note:
#   This script does not read an input file or write an output file. Only
#   explanatory comments were standardized for repository publication.
# ==============================================================================

head(data.cl_final)

# Load required packages

library(tidyverse)
library(ggcorrplot) 
library(caret)

  data_full_corr <- data.cl_final %>%
  select(
    HW_Status,
    
    # Temperatur Rohdaten
    Temp_Mean, Temp_Max, Temp_Min, Temp_Q90, Temp_SD,
    
    # Gefühlte Temperatur
    AT_Mean, AT_Max,
    
    # Population-weighted metrics
    temp_pop_w, dewpoint_pop_w, wind_pop_w,
    
    # Dew-point-temperature and wind-speed metrics
    Dew_Mean, Dew_Max, Dew_Min, Dew_Q90, Dew_SD,
    Wind_Mean, Wind_Min, Wind_Q10, Wind_SD,
    
    # 3-Tages-Trends
    D3_min, D3_max, D3_AT_Max, D3_AT_Mean,
    
    # Radiation
    Radiation_Mean, Radiation_Max, Sunshine_Hours,  D3_Rad_Max, D3_Sun_Hours
    
  ) %>%
  drop_na() 

# Calculate the Pearson correlation matrix
cor_matrix_all <- cor(data_full_corr, method = "pearson")

# Plot the lower-triangular correlation matrix 
ggcorrplot(cor_matrix_all, 
           type = "lower", 
           lab = FALSE, 
           tl.cex = 8, 
           title = "Correlation Matrix (all variables)",
           colors = c("blue", "white", "red"))

# # Identify variables exceeding the correlation cutoff (> 0.95)
high_cor_vars <- findCorrelation(cor_matrix_all, cutoff = 0.95, names = TRUE)

cat("Folgende Variablen sind stark redundant (>95%) und sollten reduziert werden:\n")
print(high_cor_vars)
