# ==============================================================================
# Script: 02_01_assemble_annual_climate_exposure_data.R
# Original file: merge_climatedata_hostrada_final.R
#
# Purpose:
#   Merges the prepared district-level daily climate exposure datasets and adds
#   population-weighted exposure estimates to create one annual climate master
#   dataset for each year.
#
# Inputs:
#   - Annual district-level daily apparent-temperature CSV files
#   - Annual district-level daily radiation CSV files
#   - Annual district-level daily air-temperature CSV files
#   - Annual district-level daily wind-speed CSV files
#   - Annual district-level daily dew-point-temperature CSV files
#   - Population-weighted daily exposure CSV files for air temperature,
#     wind speed, and dew-point temperature
#
# Outputs:
#   - One annual CSV file named Climate_Master_Daily_<year>.csv containing the
#     assembled district-level daily climate exposure variables
#
# Spatial unit:
#   Harmonized German administrative districts identified by AGS
#
# Temporal coverage:
#   2000–2022
#
# Required packages:
#   dplyr, stringr, readr, purrr
#
# Dependencies:
#   Requires the outputs generated by the exposure-preparation scripts in
#   01_Exposure_Preparation.
#
# Repository note:
#   Paths are project-relative and assume that the working directory is set to
#   the repository root. Only path strings and explanatory comments were
#   standardized for repository publication.
# ==============================================================================

# Load required packages

library(dplyr)
library(stringr) 
library(readr)
library(purrr)

####################
## SETUP & CONFIG ##
####################

# Output directory
path_final_output <- "data/intermediate/data_assembly/annual_climate_data"

# Input directories
path_at   <- "data/intermediate/exposure/daily_apparent_temperature"
path_rad  <- "data/intermediate/exposure/daily_downwelling_radiation"
path_temp <- "data/intermediate/exposure/daily_air_temperature"
path_wind <- "data/intermediate/exposure/daily_wind_speed"
path_dew  <- "data/intermediate/exposure/daily_dew_point_temperature"

path_pop_results <- "data/intermediate/exposure/population_weighted"

if(!dir.exists(path_final_output)) dir.create(path_final_output)

load_pop <- function(name) {
  read_csv(file.path(path_pop_results, name), show_col_types = FALSE) %>%
    mutate(AGS = str_pad(as.character(AGS), width = 5, pad = "0", side = "left"), 
           Datum = as.Date(Datum))
}

# Load population-weighted exposure data
df_pop_t <- load_pop("temp_DAILY_pop_weighted.csv")
df_pop_w <- load_pop("wind_DAILY_pop_weighted.csv")
df_pop_d <- load_pop("dewpoint_DAILY_pop_weighted.csv")


# Merge population-weighted exposure datasets
df_pop_all <- df_pop_t %>%
  full_join(df_pop_w, by = c("AGS", "Datum")) %>%
  full_join(df_pop_d, by = c("AGS", "Datum"))

# Remove temporary objects and release memory
rm(df_pop_t, df_pop_w, df_pop_d)
gc()

# Process data by year

years <- 2000:2022

for (yr in years) {
  print(paste(">>> Erstelle Master für Jahr:", yr, "<<<"))
  
  # Dateinamen für dieses Jahr bauen
  f_at   <- file.path(path_at,   paste0("AT_Kreise_Daily_", yr, ".csv"))
  f_rad  <- file.path(path_rad,  paste0("Radiation_Kreise_Daily_", yr, ".csv"))
  f_temp <- file.path(path_temp, paste0("Temperature_Kreise_Daily_", yr, ".csv"))
  f_wind <- file.path(path_wind, paste0("Wind_Kreise_Daily_", yr, ".csv"))
  f_dew  <- file.path(path_dew,  paste0("Dewpoint_Kreise_Daily_", yr, ".csv"))
  
  # Check
  if (!all(file.exists(f_at, f_rad, f_temp, f_wind, f_dew))) {
    print(paste("WARNUNG: Dateien fehlen für Jahr", yr, "- überspringe!"))
    next
  }
  
  # Read annual input files
  d_at   <- read_csv(f_at, show_col_types = FALSE)
  d_rad  <- read_csv(f_rad, show_col_types = FALSE)
  d_temp <- read_csv(f_temp, show_col_types = FALSE)
  d_wind <- read_csv(f_wind, show_col_types = FALSE)
  d_dew  <- read_csv(f_dew, show_col_types = FALSE)
  
  # Merge
  list_of_dfs <- list(d_at, d_rad, d_temp, d_wind, d_dew)
  
  # Merge annual climate exposure datasets
  df_year_clim <- list_of_dfs %>%
    purrr::reduce(full_join, by = c("AGS", "Datum")) %>%
    mutate(
      AGS = str_pad(as.character(AGS), width = 5, pad = "0", side = "left"),
      Datum = as.Date(Datum)
    )
  
  # Add population-weighted exposure estimates
  df_final <- left_join(df_year_clim, df_pop_all, by = c("AGS", "Datum"))
  
  # Speichern
  outfile <- file.path(path_final_output, paste0("Climate_Master_Daily_", yr, ".csv"))
  write_csv(df_final, outfile)
  print(paste("   Gespeichert:", basename(outfile)))
  
  # Aufräumen 
  rm(d_at, d_rad, d_temp, d_wind, d_dew, df_year_clim, df_final, list_of_dfs)
  gc()
}
