# ==============================================================================
# Script: 05_07_configure_period_specific_first_stage_models.R
#
# Purpose:
#   Defines the computing environment, paths, outcomes, alert variables, model
#   parameters, and logging settings for separate district-specific analyses of
#   the pre-implementation and post-implementation periods.
#
# Paired analysis script:
#   05_08_fit_period_specific_first_stage_models.R
#
# Inputs:
#   - District-specific daily time-series CSV files generated by
#     05_02_create_ags_timeseries.R
#
# Outputs:
#   - Separate district-specific first-stage estimates for 2000–2004 and
#     2005–2009
#   - District-exclusion file
#   - Model error log
#   - Execution log
#
# Analysis periods:
#   Pre-implementation:  May–September, 2000–2004
#   Post-implementation: May–September, 2005–2009
#
# Required packages:
#   data.table, dplyr, splines, dlnm
#
# Data access:
#   Hospital data and district-specific input files are restricted and are not
#   included in the repository.
#
# Repository note:
#   Paths may require adaptation to the approved secure
#   FDZ computing environment before execution. File names, path strings,
#   and explanatory comments were standardized.
# ==============================================================================

# =====================================================================
# 1. LADEN VON PACKAGES
# =====================================================================

library(data.table)
library(dplyr)
library(splines)
library(dlnm)

# =====================================================================
# 2. SPEICHER LEEREN
# =====================================================================

rm(list=ls())

# =====================================================================
# 3. DEFINITION ARBEITSUMGEBUNG
# =====================================================================

FDZ <- 1

if (FDZ == 0) {
  input_path  <- "data/restricted/local/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/local/period_specific"
  syntax_path <- "R/05_FDZ_Analyses"
}

if (FDZ == 1) {
  input_path  <- "data/restricted/fdz/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/fdz/period_specific"
  syntax_path <- "R/05_FDZ_Analyses"
}

# =====================================================================
# 4. MAKROS & MODEL-PARAMETER
# =====================================================================

syntax_name <- "05_08_fit_period_specific_first_stage_models"
log_file_name <- "Log_FirstStage_GetrenntePerioden.txt"


diagnoses_to_analyze <- c("AllAdmissions", "Resp_0", "Uri_0", "Infect_par")

vars_to_aggregate <- c(
  "Infect_par", "Resp_0", "Resp_1", "Resp_2",
  "Card_0", "Card_1", "Card_2", "Ment_0", "Ment_1",
  "Uri_0",  "Uri_1",  "Uri_2", "Other"
)

# Zeitraum-Filter (Mai bis September)
months_analysis <- 5:9         

# RFM Liste
rfm_list <- c("heat_alerts_rfm1", "heat_alerts_rfm2", 
              "heat_alerts_rfm3", "heat_alerts_rfm4", "heat_alerts_rfm5")

# Modell-Spezifikationen (DLNM)
varfun    <- "bs"          
vardegree <- 2             
varper    <- c(50, 90)     
lag       <- 3             
dfseas    <- 4             
dftrend   <- 1             

# START DER AUFZEICHNUNG
if(!dir.exists(output_path)) dir.create(output_path, recursive = TRUE)
sink(file.path(output_path, log_file_name), type = c("output", "message"), split = TRUE)

# =======================================================================
# 5. AUSFÜHRUNG ANALYSE-SKRIPT
# =======================================================================

source(file.path(syntax_path, paste0(syntax_name, ".R")), echo = TRUE, max.deparse.length = 99999)

print("Skript beendet. Schließe Log.")

sink()
