# ==============================================================================
# Script: 05_05_configure_cause_specific_first_stage_models.R
#
# Purpose:
#   Defines the computing environment, input and output paths, diagnosis
#   variables, model parameters, analysis period, Random Forest alert variables,
#   and logging settings for the district-specific cause-specific first-stage
#   analysis.
#
# Paired analysis script:
#   05_06_fit_cause_specific_first_stage_models.R
#
# Inputs:
#   - District-specific daily time-series CSV files generated by
#     05_02_create_ags_timeseries.R
#
# Outputs:
#   - District-specific cause-specific first-stage model estimates
#   - District-exclusion file
#   - Model error log
#   - Execution log
#
# Outcomes:
#   - Respiratory admissions
#   - Genitourinary admissions
#   - Infectious and parasitic disease admissions
#
# Analysis period:
#   May–September, 2000–2009
#
# Required packages:
#   data.table, dplyr, splines, dlnm
#
# Data access:
#   Hospital data and district-specific input files are restricted and are not
#   included in the repository.
#
# Repository note:
#   Paths may require adaptation to the approved secure
#   FDZ computing environment before execution. File names, path strings,
#   and explanatory comments were standardized.
# ==============================================================================

# =====================================================================
# 1. LADEN VON PACKAGES
# =====================================================================

library(data.table)
library(dplyr)
library(splines)
library(dlnm)

# =====================================================================
# 2. SPEICHER LEEREN
# =====================================================================

rm(list=ls())

# =====================================================================
# 3. DEFINITION ARBEITSUMGEBUNG
# =====================================================================

FDZ <- 1

if (FDZ == 0) {
  input_path  <- "data/restricted/local/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/local/cause_specific"
  syntax_path <- "R/05_FDZ_Analyses"
}

if (FDZ == 1) {
  input_path  <- "data/restricted/fdz/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/fdz/cause_specific"
  syntax_path <- "R/05_FDZ_Analyses"
}

# =====================================================================
# 4. MAKROS & STRATA
# =====================================================================

syntax_name <- "05_06_fit_cause_specific_first_stage_models"
log_file_name <- "Log_FirstStage_Regression_Diagnosen.txt"

# Diagnosen
diagnoses_to_analyze <- c("Resp_0", "Uri_0", "Infect_par")

# Zeitraum-Filter 
years_analysis  <- 2000:2009   
months_analysis <- 5:9         

# Modell-Spezifikationen (DLNM)
rfm_list <- c("heat_alerts_rfm1", "heat_alerts_rfm2", 
              "heat_alerts_rfm3", "heat_alerts_rfm4", "heat_alerts_rfm5")

varfun    <- "bs"          # Basis-Funktion Temp
vardegree <- 2             # Grad
varper    <- c(50, 90)     # Knots (Perzentile)
lag       <- 3             # Lag in Tagen
dfseas    <- 4             # Freiheitsgrade Saison
dftrend   <- 1             # Freiheitsgrade Trend

# START DER AUFZEICHNUNG
if(!dir.exists(output_path)) dir.create(output_path, recursive = TRUE)
sink(file.path(output_path, log_file_name), type = c("output", "message"), split = TRUE)

# =======================================================================
# 5. AUSFÜHRUNG ANALYSE-SKRIPT
# =======================================================================

source(file.path(syntax_path, paste0(syntax_name, ".R")), echo = TRUE, max.deparse.length = 99999)

print("Skript beendet. Schließe Log.")

sink()
