# ==============================================================================
# Script: 05_11_configure_combined_first_stage_and_sensitivity_models.R
#
# Purpose:
#   Defines the computing environment, input and output paths, outcomes, Random
#   Forest alert variables, model parameters, degrees-of-freedom sensitivity
#   settings, and logging parameters for the combined all-cause and
#   cause-specific first-stage analysis.
#
# Paired analysis script:
#   05_12_fit_combined_first_stage_and_sensitivity_models.R
#
# Inputs:
#   - District-specific daily time-series CSV files generated by
#     05_02_create_ags_timeseries.R
#
# Outputs:
#   - District-specific primary first-stage estimates
#   - Degrees-of-freedom sensitivity estimates
#   - District-exclusion file
#   - Model error log
#   - Execution log, where generated by the complete configuration script
#
# Configured outcomes:
#   - All-cause admissions
#   - Respiratory admissions
#   - Genitourinary admissions
#   - Infectious and parasitic disease admissions
#   - Cardiovascular admissions
#
# Primary analysis period:
#   May–September, 2000–2009
#
# Available source-data period:
#   2000–2022
#
# Required packages:
#   data.table, dplyr, splines, dlnm
#
# Data access:
#   Hospital data and district-specific input files are restricted and are not
#   included in the repository.
#
# Repository note:
#   Paths may require adaptation to the approved secure
#   FDZ computing environment before execution. File names, path strings,
#   and explanatory comments were standardized.
# ==============================================================================

# =====================================================================
# 1. LADEN VON PACKAGES
# =====================================================================

library(data.table)
library(dplyr)
library(splines)
library(dlnm)

# =====================================================================
# 2. SPEICHER LEEREN
# =====================================================================

rm(list=ls())

# =====================================================================
# 3. DEFINITION ARBEITSUMGEBUNG
# =====================================================================

FDZ <- 1

if (FDZ == 0) {
  input_path  <- "data/restricted/local/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/local/combined_sensitivity"
  syntax_path <- "R/05_FDZ_Analyses"
}

if (FDZ == 1) {
  input_path  <- "data/restricted/fdz/ags_timeseries"
  output_path <- "outputs/05_fdz_analyses/fdz/combined_sensitivity"
  syntax_path <- "R/05_FDZ_Analyses"
}

# =====================================================================
# 4. MAKROS & MODEL-PARAMETER
# =====================================================================

syntax_name <- "05_12_fit_combined_first_stage_and_sensitivity_models"
log_file_name <- "Log_FirstStage_Regression_2000-2009.txt"

# Diagnosen (Card_0 hinzugefügt)
diagnoses_to_analyze <- c("All_Cause", "Resp_0", "Uri_0", "Infect_par", "Card_0")

# Zeitraum-Filter 
years_analysis  <- 2000:2009   
months_analysis <- 5:9         

# Modell-Spezifikationen (DLNM)
rfm_list <- c("heat_alerts_rfm1", "heat_alerts_rfm2", 
              "heat_alerts_rfm3", "heat_alerts_rfm4", "heat_alerts_rfm5")

varfun    <- "bs"          # Basis-Funktion Temp
vardegree <- 2             # Grad
varper    <- c(50, 90)     # Knots (Perzentile)
lag       <- 3             # Lag in Tagen
dfseas    <- 4             # Freiheitsgrade Saison
dftrend   <- 1             # Freiheitsgrade Trend

# Parameter für den Over-Adjustment Sensitivitätstest
df_sens_list <- c(3, 4, 5)

# =====================================================================
# 5. START DER AUFZEICHNUNG & AUSFÜHRUNG
# =====================================================================

if(!dir.exists(output_path)) dir.create(output_path, recursive = TRUE)
